sudo: enabled
service:
  - docker

#before_install:
#  - echo "mock"
#  - docker build -t odushyn/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true odushyn/react-test npm run test
#after_success:
script:
  - docker build -t $DOCKER_ID/udemy-complex-client ./client
  - docker build -t $DOCKER_ID/udemy-complex-nginx ./nginx
  - docker build -t $DOCKER_ID/udemy-complex-server ./server
  - docker build -t $DOCKER_ID/udemy-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/udemy-complex-client
  - docker push $DOCKER_ID/udemy-complex-nginx
  - docker push $DOCKER_ID/udemy-complex-server
  - docker push $DOCKER_ID/udemy-complex-worker
deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker-u-complex"
  env: "DockerUComplex-env"
  bucket_name: "elasticbeanstalk-us-east-2-702433753249"
  bucket_path: "docker-u-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY