sudo: enabled
service:
  - docker

#before_install:
#  - echo "mock"
#  - docker build -t odushyn/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true odushyn/react-test npm run test
#after_success:
script:
  - docker build -t $DOCKER_ID/udemy-complex-client ./client
  - docker build -t $DOCKER_ID/udemy-complex-nginx ./nginx
  - docker build -t $DOCKER_ID/udemy-complex-server ./server
  - docker build -t $DOCKER_ID/udemy-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/udemy-complex-client
  - docker push $DOCKER_ID/udemy-complex-nginx
  - docker push $DOCKER_ID/udemy-complex-server
  - docker push $DOCKER_ID/udemy-complex-worker
